### ISSUE TITLE
About button not working 

### ISSUE THREAD

**Issue by Rajsona123** [HarshalPurohitEdits/TheMovieProviderBot#7]
Bhai About button Aur Text Mode me Premium Button File stream me kaam nahi kar raha hai, Aur Streaam par agar shortner use nahi karte hai to stream work nahi kar raha  hai, esko fix kijiye

**Comment by HarshalPurohitEdits** [comment]
About button is working perfectly !
Text mode premium fixed.
Shortner on stream link working perfectly !
